name: CI

on: push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 18.x

      - name: Install packages
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish into gh-pages
        if: github.ref == 'refs/heads/main'
        uses: s0/git-publish-subdir-action@v2.6.0
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
