name: CI

on: push

env:
  WORKING_DIR: ./playground

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install packages
        run: npm ci
        working-directory: ${{ env.WORKING_DIR }}

      - name: Build
        run: npm run build
        working-directory: ${{ env.WORKING_DIR }}

      - name: Deploy Function App
        #if: github.ref == 'refs/heads/main'
        run: npm run deploy
        working-directory: ${{ env.WORKING_DIR }}
